# Generated by Django 5.1.4 on 2025-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal User"),
                            ("entrepreneur", "Entrepreneur"),
                            ("researcher", "Researcher"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="my_model",
        ),
    ]
