# Generated by Django 5.1.4 on 2025-02-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_admin_entrepreneur_governmentengineer_normaluser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_id", models.IntegerField(max_length=5)),
                ("role_names", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(max_length=1000)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("normal", "Normal User"),
                            ("entrepreneur", "Entrepreneur"),
                            ("researcher", "Researcher"),
                            ("govt. engineer", "Government Engineer"),
                            ("admin", "Admin"),
                        ],
                        max_length=50,
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="Entrepreneur",
        ),
        migrations.DeleteModel(
            name="GovernmentEngineer",
        ),
        migrations.DeleteModel(
            name="NormalUser",
        ),
        migrations.DeleteModel(
            name="Researcher",
        ),
        migrations.AddField(
            model_name="roles",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
            ),
        ),
    ]
