# Generated by Django 4.2.19 on 2025-02-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_roles_users_delete_admin_delete_entrepreneur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Userstable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name="roles",
            name="role_id",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="roles",
            name="role_names",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_users",
                to="myapp.roles",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="myapp.userstable",
            ),
        ),
    ]
